from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL


class TimeStampMixin(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="%(class)s_created",
        default=1,
    )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="%(class)s_updated",
        default=1,
    )

    class Meta:
        abstract = True


APPLICATION_STATUS_LIST = [
    ("PENDING", "PENDING"),
    ("APPROVED", "APPROVED"),
    ("REJECTED", "REJECTED"),
]

AGENCY_REFERRAL_LIST = [
    ("RED CROSS", "RED CROSS"),
    ("HUMAN SERVICES", "HUMAN SERVICES"),
    ("CONSTITUENCY COUNCIL", "CONSTITUENCY COUNCIL"),
    (
        "SAINT LUCIA SOCIAL DEVELOPMENT FUND (SSDF)",
        "SAINT LUCIA SOCIAL DEVELOPMENT FUND (SSDF)",
    ),
    ("OTHER", "OTHER"),
]

LAND_USE_LIST = [
    ("RESIDENTIAL", "RESIDENTIAL"),
    ("COMMERCIAL", "COMMERCIAL"),
    ("INDUSTRIAL", "INDUSTRIAL"),
    ("TOURISTIC", "TOURISTIC"),
    ("AGRICULTURAL", "AGRICULTURAL"),
    ("INSTITUTIONAL", "INSTITUTIONAL"),
    ("SIGNAGE", "SIGNAGE"),
    ("OTHER", "OTHER"),
]

EASEMENT_LIST = [
    ("WATER CONNECTION", "WATER CONNECTION"),
    ("ELECTRICITY", "ELECTRICITY"),
    ("PEDESTRIAN RIGHT OF WAY", "PEDESTRIAN RIGHT OF WAY"),
    ("VEHICULAR RIGHT OF WAY", "VEHICULAR RIGHT OF WAY"),
    ("DRAINAGE", "DRAINAGE"),
    ("OTHER", "OTHER"),
]

APPLICATION_TYPE = [
    ("PURCHASE", "PURCHASE"),
    ("LEASE", "LEASE"),
    ("LEASE RENEWAL", "LEASE RENEWAL"),
]

OFFICE_LIST = [
    ("CASTRIES", "CASTRIES"),
    ("VIEUX FORT", "VIEUX FORT"),
]


TYPE_OF_IDENTIFICATION_LIST = [
    ("NATIONAL ID", "NATIONAL ID"),
    ("PASSPORT", "PASSPORT"),
    ("DRIVER'S LICENCE", "DRIVER'S LICENCE"),
]

TITLE_LIST = [
    ("MR", "MR"),
    ("MRS", "MRS"),
    ("MS", "MS"),
]

GRADE_LIST = [
    ("1", "1"),
    ("2", "2"),
    ("3", "3"),
    ("4", "4"),
]

POSITION_LIST = [
    ("CLERK", "CLERK"),
    ("SECRETARY", "SECRETARY"),
    ("CROWN LANDS TECHNICIAN", "CROWN LANDS TECHNICIAN"),
    ("CROWN LANDS ASSISTANT", "CROWN LANDS ASSISTANT"),
    ("CROWN LANDS OFFICER", "CROWN LANDS OFFICER"),
    ("SURVEYER", "SURVEYER"),
    ("DEPUTY COMMISSIONER OF CROWN LANDS", "DEPUTY COMMISSIONER OF CROWN LANDS"),
    ("COMMISSIONER OF CROWN LANDS", "COMMISSIONER OF CROWN LANDS"),
]

QUARTER_LIST = [
    ("GROS ISLET", "GROS ISLET"),
    ("CASTRIES", "CASTRIES"),
    ("CANARIES", "CANARIES"),
    ("SOUFRIERE", "SOUFRIERE"),
    ("LABORIE", "LABORIE"),
    ("VIEUX FORT", "VIEUX FORT"),
    ("MICOUD", "MICOUD"),
]


COMMUNITY_LIST = [
    ("ROCK HALL", "ROCK HALL"),
    ("PAVEE", "PAVEE"),
    ("MORNE FORTUNE", "MORNE FORTUNE"),
    ("DERRIERE", "DERRIERE"),
    ("BEXON", "BEXON"),
    ("CAS EN BAS", "CAS EN BAS"),
]

NATIONALITY_LIST = (
    ("Afghan", "Afghan"),
    ("Albanian", "Albanian"),
    ("Algerian", "Algerian"),
    ("American", "American"),
    ("Andorran", "Andorran"),
    ("Angolan", "Angolan"),
    ("Antiguans", "Antiguans"),
    ("Argentinean", "Argentinean"),
    ("Armenian", "Armenian"),
    ("Australian", "Australian"),
    ("Austrian", "Austrian"),
    ("Azerbaijani", "Azerbaijani"),
    ("Bahamian", "Bahamian"),
    ("Bahraini", "Bahraini"),
    ("Bangladeshi", "Bangladeshi"),
    ("Barbadian", "Barbadian"),
    ("Barbudans", "Barbudans"),
    ("Batswana", "Batswana"),
    ("Belarusian", "Belarusian"),
    ("Belgian", "Belgian"),
    ("Belizean", "Belizean"),
    ("Beninese", "Beninese"),
    ("Bhutanese", "Bhutanese"),
    ("Bolivian", "Bolivian"),
    ("Bosnian", "Bosnian"),
    ("Brazilian", "Brazilian"),
    ("British", "British"),
    ("Bruneian", "Bruneian"),
    ("Bulgarian", "Bulgarian"),
    ("Burkinabe", "Burkinabe"),
    ("Burmese", "Burmese"),
    ("Burundian", "Burundian"),
    ("Cambodian", "Cambodian"),
    ("Cameroonian", "Cameroonian"),
    ("Canadian", "Canadian"),
    ("Cape Verdean", "Cape Verdean"),
    ("Central African", "Central African"),
    ("Chadian", "Chadian"),
    ("Chilean", "Chilean"),
    ("Chinese", "Chinese"),
    ("Colombian", "Colombian"),
    ("Comoran", "Comoran"),
    ("Congolese", "Congolese"),
    ("Costa Rican", "Costa Rican"),
    ("Croatian", "Croatian"),
    ("Cuban", "Cuban"),
    ("Cypriot", "Cypriot"),
    ("Czech", "Czech"),
    ("Danish", "Danish"),
    ("Djibouti", "Djibouti"),
    ("Dominican", "Dominican"),
    ("Dutch", "Dutch"),
    ("Dutchman", "Dutchman"),
    ("Dutchwoman", "Dutchwoman"),
    ("East Timorese", "East Timorese"),
    ("Ecuadorean", "Ecuadorean"),
    ("Egyptian", "Egyptian"),
    ("Emirian", "Emirian"),
    ("Equatorial Guinean", "Equatorial Guinean"),
    ("Eritrean", "Eritrean"),
    ("Estonian", "Estonian"),
    ("Ethiopian", "Ethiopian"),
    ("Fijian", "Fijian"),
    ("Filipino", "Filipino"),
    ("Finnish", "Finnish"),
    ("French", "French"),
    ("Gabonese", "Gabonese"),
    ("Gambian", "Gambian"),
    ("Georgian", "Georgian"),
    ("German", "German"),
    ("Ghanaian", "Ghanaian"),
    ("Greek", "Greek"),
    ("Grenadian", "Grenadian"),
    ("Guatemalan", "Guatemalan"),
    ("Guinea-Bissauan", "Guinea-Bissauan"),
    ("Guinean", "Guinean"),
    ("Guyanese", "Guyanese"),
    ("Haitian", "Haitian"),
    ("Herzegovinian", "Herzegovinian"),
    ("Honduran", "Honduran"),
    ("Hungarian", "Hungarian"),
    ("I-Kiribati", "I-Kiribati"),
    ("Icelander", "Icelander"),
    ("Indian", "Indian"),
    ("Indonesian", "Indonesian"),
    ("Iranian", "Iranian"),
    ("Iraqi", "Iraqi"),
    ("Irish", "Irish"),
    ("Israeli", "Israeli"),
    ("Italian", "Italian"),
    ("Ivorian", "Ivorian"),
    ("Jamaican", "Jamaican"),
    ("Japanese", "Japanese"),
    ("Jordanian", "Jordanian"),
    ("Kazakhstani", "Kazakhstani"),
    ("Kenyan", "Kenyan"),
    ("Kittian and Nevisian", "Kittian and Nevisian"),
    ("Kuwaiti", "Kuwaiti"),
    ("Kyrgyz", "Kyrgyz"),
    ("Laotian", "Laotian"),
    ("Latvian", "Latvian"),
    ("Lebanese", "Lebanese"),
    ("Liberian", "Liberian"),
    ("Libyan", "Libyan"),
    ("Liechtensteiner", "Liechtensteiner"),
    ("Lithuanian", "Lithuanian"),
    ("Luxembourger", "Luxembourger"),
    ("Macedonian", "Macedonian"),
    ("Malagasy", "Malagasy"),
    ("Malawian", "Malawian"),
    ("Malaysian", "Malaysian"),
    ("Maldivan", "Maldivan"),
    ("Malian", "Malian"),
    ("Maltese", "Maltese"),
    ("Marshallese", "Marshallese"),
    ("Mauritanian", "Mauritanian"),
    ("Mauritian", "Mauritian"),
    ("Mexican", "Mexican"),
    ("Micronesian", "Micronesian"),
    ("Moldovan", "Moldovan"),
    ("Monacan", "Monacan"),
    ("Mongolian", "Mongolian"),
    ("Moroccan", "Moroccan"),
    ("Mosotho", "Mosotho"),
    ("Motswana", "Motswana"),
    ("Mozambican", "Mozambican"),
    ("Namibian", "Namibian"),
    ("Nauruan", "Nauruan"),
    ("Nepalese", "Nepalese"),
    ("Netherlander", "Netherlander"),
    ("New Zealander", "New Zealander"),
    ("Ni-Vanuatu", "Ni-Vanuatu"),
    ("Nicaraguan", "Nicaraguan"),
    ("Nigerian", "Nigerian"),
    ("Nigerien", "Nigerien"),
    ("North Korean", "North Korean"),
    ("Northern Irish", "Northern Irish"),
    ("Norwegian", "Norwegian"),
    ("Omani", "Omani"),
    ("Pakistani", "Pakistani"),
    ("Palauan", "Palauan"),
    ("Panamanian", "Panamanian"),
    ("Papua New Guinean", "Papua New Guinean"),
    ("Paraguayan", "Paraguayan"),
    ("Peruvian", "Peruvian"),
    ("Polish", "Polish"),
    ("Portuguese", "Portuguese"),
    ("Qatari", "Qatari"),
    ("Romanian", "Romanian"),
    ("Russian", "Russian"),
    ("Rwandan", "Rwandan"),
    ("Saint Lucian", "Saint Lucian"),
    ("Salvadoran", "Salvadoran"),
    ("Samoan", "Samoan"),
    ("San Marinese", "San Marinese"),
    ("Sao Tomean", "Sao Tomean"),
    ("Saudi", "Saudi"),
    ("Scottish", "Scottish"),
    ("Senegalese", "Senegalese"),
    ("Serbian", "Serbian"),
    ("Seychellois", "Seychellois"),
    ("Sierra Leonean", "Sierra Leonean"),
    ("Singaporean", "Singaporean"),
    ("Slovakian", "Slovakian"),
    ("Slovenian", "Slovenian"),
    ("Solomon Islander", "Solomon Islander"),
    ("Somali", "Somali"),
    ("South African", "South African"),
    ("South Korean", "South Korean"),
    ("Spanish", "Spanish"),
    ("Sri Lankan", "Sri Lankan"),
    ("Sudanese", "Sudanese"),
    ("Surinamer", "Surinamer"),
    ("Swazi", "Swazi"),
    ("Swedish", "Swedish"),
    ("Swiss", "Swiss"),
    ("Syrian", "Syrian"),
    ("Taiwanese", "Taiwanese"),
    ("Tajik", "Tajik"),
    ("Tanzanian", "Tanzanian"),
    ("Thai", "Thai"),
    ("Togolese", "Togolese"),
    ("Tongan", "Tongan"),
    ("Trinidadian or Tobagonian", "Trinidadian or Tobagonian"),
    ("Tunisian", "Tunisian"),
    ("Turkish", "Turkish"),
    ("Tuvaluan", "Tuvaluan"),
    ("Ugandan", "Ugandan"),
    ("Ukrainian", "Ukrainian"),
    ("Uruguayan", "Uruguayan"),
    ("Uzbekistani", "Uzbekistani"),
    ("Venezuelan", "Venezuelan"),
    ("Vietnamese", "Vietnamese"),
    ("Welsh", "Welsh"),
    ("Yemenite", "Yemenite"),
    ("Zambian", "Zambian"),
    ("Zimbabwean", "Zimbabwean"),
)
