# Generated by Django 3.2.5 on 2021-07-16 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('block', models.CharField(max_length=5, null=True, unique=True)),
                ('parcel', models.CharField(max_length=3, null=True, unique=True)),
                ('community', models.CharField(choices=[('ROCK HALL', 'ROCK HALL'), ('PAVEE', 'PAVEE'), ('MORNE FORTUNE', 'MORNE FORTUNE'), ('DERRIERE', 'DERRIERE'), ('BEXON', 'BEXON'), ('CAS EN BAS', 'CAS EN BAS')], max_length=50)),
                ('is_occupied', models.BooleanField(blank=True, default=False)),
                ('is_acquired', models.BooleanField(blank=True, default=False)),
                ('is_leased', models.BooleanField(blank=True, default=False)),
                ('is_queen_chain', models.BooleanField(blank=True, default=False, verbose_name="queen's chain")),
                ('is_available', models.BooleanField(blank=True, default=False)),
                ('area_requested', models.CharField(blank=True, help_text='(imperial/metric)', max_length=10, null=True)),
                ('occupied_by_me', models.BooleanField(blank=True, default=False)),
                ('years_occupied_by_me', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'unique_together': {('block', 'parcel')},
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('survey_plan_no', models.CharField(blank=True, max_length=200, unique=True)),
                ('survey_plan', models.FileField(blank=True, upload_to=properties.models.survey_plans_directory_path)),
                ('date_surveyed', models.DateTimeField(blank=True)),
                ('parcel_h', models.PositiveIntegerField(default=0, verbose_name='hectares')),
                ('parcel_f', models.PositiveIntegerField(default=0, verbose_name='feet')),
                ('parcel_m', models.PositiveIntegerField(default=0, verbose_name='metres')),
                ('noted', models.TextField(blank=True)),
                ('block_parcel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='properties.property')),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
