# Generated by Django 3.2.5 on 2021-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='quarter',
            field=models.CharField(choices=[('GROS ISLET', 'GROS ISLET'), ('CASTRIES', 'CASTRIES'), ('CANARIES', 'CANARIES'), ('SOUFRIERE', 'SOUFRIERE'), ('LABORIE', 'LABORIE'), ('VIEUX FORT', 'VIEUX FORT'), ('MICOUD', 'MICOUD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='community',
            field=models.CharField(choices=[('ROCK HALL', 'ROCK HALL'), ('PAVEE', 'PAVEE'), ('UNION', 'UNION'), ('BATATA', 'BATATA'), ('TI MORNE', 'TI MORNE'), ('MORNE FORTUNE', 'MORNE FORTUNE'), ('DERRIERE', 'DERRIERE'), ('BEXON', 'BEXON'), ('CAS EN BAS', 'CAS EN BAS')], max_length=50),
        ),
    ]
