# Generated by Django 3.2.5 on 2021-07-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('properties', '0002_auto_20210717_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_communities', to='locations.communitylist'),
        ),
    ]
