# Generated by Django 3.2.5 on 2021-07-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210717_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area_requested',
        ),
    ]
