# Generated by Django 3.2.5 on 2021-07-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_area_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='noted',
            new_name='notes',
        ),
    ]
