# Generated by Django 3.2.5 on 2021-07-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_noted_survey_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_plan',
            field=models.FileField(blank=True, upload_to='survey_plans'),
        ),
    ]
