# Generated by Django 3.2.5 on 2021-07-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_survey_survey_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_plan',
            field=models.FileField(blank=True, upload_to='survey_plans_directory_path'),
        ),
    ]
