# Generated by Django 3.2.5 on 2021-07-17 22:43

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_survey_survey_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_surveyed',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_plan',
            field=models.FileField(blank=True, upload_to=properties.models.survey_plans_directory_path),
        ),
    ]
