# Generated by Django 3.2.5 on 2021-07-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20210717_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='date_surveyed',
        ),
    ]
