# Generated by Django 3.2.5 on 2021-07-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_survey_date_surveyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date_surveyed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_plan_no',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
