# Generated by Django 3.2.5 on 2021-07-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20210717_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_plan_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
