# Generated by Django 3.2.5 on 2021-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_survey_survey_plan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='block',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parcel',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
