# Generated by Django 3.2.5 on 2021-07-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_identification_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
