# Generated by Django 3.2.5 on 2021-07-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_individual_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='id_type',
            field=models.CharField(choices=[('NATIONAL ID', 'NATIONAL ID'), ('PASSPORT', 'PASSPORT'), ("DRIVER'S LICENCE", "DRIVER'S LICENCE")], max_length=50, verbose_name='Type'),
        ),
    ]
