# Generated by Django 3.2.5 on 2021-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_identification_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='community',
            field=models.CharField(blank=True, choices=[('ROCK HALL', 'ROCK HALL'), ('PAVEE', 'PAVEE'), ('UNION', 'UNION'), ('BATATA', 'BATATA'), ('TI MORNE', 'TI MORNE'), ('MORNE FORTUNE', 'MORNE FORTUNE'), ('DERRIERE', 'DERRIERE'), ('BEXON', 'BEXON'), ('CAS EN BAS', 'CAS EN BAS')], max_length=50),
        ),
    ]
