# Generated by Django 3.2.5 on 2021-07-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('clients', '0005_alter_individual_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_quarters', to='locations.quarterlist'),
        ),
    ]
