# Generated by Django 3.2.5 on 2021-07-16 09:41

import applications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0002_remove_employee_email'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('filing_number', models.CharField(blank=True, max_length=200, unique=True)),
                ('applicant_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='pending', max_length=20)),
                ('application_type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('LEASE', 'LEASE'), ('LEASE RENEWAL', 'LEASE RENEWAL')], default='PURCHASE', max_length=20)),
                ('received_at', models.CharField(choices=[('CASTRIES', 'CASTRIES'), ('VIEUX FORT', 'VIEUX FORT')], default='CASTRIES', max_length=20)),
                ('land_use', models.CharField(choices=[('RESIDENTIAL', 'RESIDENTIAL'), ('COMMERCIAL', 'COMMERCIAL'), ('INDUSTRIAL', 'INDUSTRIAL'), ('TOURISTIC', 'TOURISTIC'), ('AGRICULTURAL', 'AGRICULTURAL'), ('INSTITUTIONAL', 'INSTITUTIONAL'), ('SIGNAGE', 'SIGNAGE'), ('OTHER', 'OTHER')], default='RESIDENTIAL', max_length=20)),
                ('land_uses', models.CharField(blank=True, max_length=200, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('easement', models.CharField(choices=[('WATER CONNECTION', 'WATER CONNECTION'), ('ELECTRICITY', 'ELECTRICITY'), ('PEDESTRIAN RIGHT OF WAY', 'PEDESTRIAN RIGHT OF WAY'), ('VEHICULAR RIGHT OF WAY', 'VEHICULAR RIGHT OF WAY'), ('DRAINAGE', 'DRAINAGE'), ('OTHER', 'OTHER')], default='WATER CONNECTION', max_length=25)),
                ('other_easement', models.CharField(blank=True, max_length=200, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to=applications.models.application_documents_directory_path)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.individual')),
                ('block_parcel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualapplication_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualapplication_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_applications', to='applications.individualapplication')),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignapplication_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignapplication_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
