# Generated by Django 3.2.5 on 2021-07-17 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
        ('employees', '0002_remove_employee_email'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualapplication',
            name='block_parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualapplication_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='easement',
            field=models.ManyToManyField(to='applications.Easement'),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='land_use',
            field=models.ManyToManyField(to='applications.LandUse'),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_statuses', to='applications.applicationstatus'),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualapplication_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='easement',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='easement_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='easement',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='easement_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignapplication',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_applications', to='applications.individualapplication'),
        ),
        migrations.AddField(
            model_name='assignapplication',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignapplication_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignapplication',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='assignapplication',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignapplication_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicationtype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicationtype_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicationstatus_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicationstatus_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
