# Generated by Django 3.2.5 on 2021-07-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualapplication',
            old_name='land_uses',
            new_name='other_land_uses',
        ),
    ]
