# Generated by Django 3.2.5 on 2021-07-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualapplication',
            name='occupied_by_me',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='years_occupied_by_me',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
