# Generated by Django 3.2.5 on 2021-07-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_land_uses_individualapplication_other_land_uses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualapplication',
            old_name='applicant_number',
            new_name='application_number',
        ),
    ]
