# Generated by Django 3.2.5 on 2021-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_applicant_number_individualapplication_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualapplication',
            name='land_use',
            field=models.CharField(max_length=20),
        ),
    ]
