# Generated by Django 3.2.5 on 2021-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20210717_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualapplication',
            name='area_requested',
            field=models.CharField(blank=True, help_text='(imperial/metric)', max_length=10, null=True),
        ),
    ]
