# Generated by Django 3.2.5 on 2021-07-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('applications', '0004_individualapplication_area_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualapplication',
            name='applicant',
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='applicant',
            field=models.ManyToManyField(to='clients.Individual'),
        ),
    ]
