# Generated by Django 3.2.5 on 2021-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_individualapplication_land_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualapplication',
            name='easement',
            field=models.CharField(choices=[('WATER CONNECTION', 'WATER CONNECTION'), ('ELECTRICITY', 'ELECTRICITY'), ('PEDESTRIAN RIGHT OF WAY', 'PEDESTRIAN RIGHT OF WAY'), ('VEHICULAR RIGHT OF WAY', 'VEHICULAR RIGHT OF WAY'), ('DRAINAGE', 'DRAINAGE'), ('OTHER', 'OTHER')], default='WATER CONNECTION', max_length=255),
        ),
    ]
