# Generated by Django 3.2.5 on 2021-07-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20210717_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualapplication',
            name='is_queen_chain',
            field=models.BooleanField(blank=True, default=False, verbose_name="queen's chain"),
        ),
    ]
