# Generated by Django 3.2.5 on 2021-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_individualapplication_easement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualapplication',
            name='received_at',
            field=models.CharField(choices=[('CASTRIES', 'CASTRIES'), ('VIEUX FORT', 'VIEUX FORT')], default='CASTRIES', max_length=255),
        ),
    ]
