# Generated by Django 3.2.5 on 2021-07-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_individualapplication_is_queen_chain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualapplication',
            old_name='file',
            new_name='application_form',
        ),
        migrations.RemoveField(
            model_name='individualapplication',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='individualapplication',
            name='response_date',
        ),
    ]
