# Generated by Django 3.2.5 on 2021-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_individualapplication_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualapplication',
            name='easement',
            field=models.CharField(default='WATER CONNECTION', max_length=255),
        ),
        migrations.AlterField(
            model_name='individualapplication',
            name='land_use',
            field=models.CharField(max_length=255),
        ),
    ]
