# Generated by Django 3.2.5 on 2021-07-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20210720_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualapplication',
            name='is_queen_chain',
        ),
    ]
