# Generated by Django 3.2.5 on 2021-07-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_easement_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualapplication',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_types', to='applications.type'),
        ),
        migrations.AlterField(
            model_name='individualapplication',
            name='easement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_easements', to='applications.easement'),
        ),
        migrations.AlterField(
            model_name='individualapplication',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_statuses', to='applications.status'),
        ),
    ]
