# Generated by Django 3.2.5 on 2021-07-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20210717_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualapplication',
            name='application_type',
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='application_type',
            field=models.ManyToManyField(to='applications.Type'),
        ),
        migrations.RemoveField(
            model_name='individualapplication',
            name='easement',
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='easement',
            field=models.ManyToManyField(to='applications.Easement'),
        ),
        migrations.RemoveField(
            model_name='individualapplication',
            name='land_use',
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='land_use',
            field=models.ManyToManyField(to='applications.LandUse'),
        ),
    ]
