# Generated by Django 3.2.5 on 2021-07-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20210717_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'verbose_name_plural': 'Application Statuses'},
        ),
    ]
