# Generated by Django 3.2.5 on 2021-07-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_applicationstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualapplication',
            name='filing_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
